# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence

stages:
  - test
  - report

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  DOCKER_HOST: tcp://docker:2375
  RUNNER_IP:

before_script:
  - export DOCKER_HOST

test_all_UI_Tests:
  image: markhobson/maven-chrome
  stage: test
  script:
    - echo "######### THREAD COUNT IS = $THREAD_COUNT"
    - mvn clean test -Dcucumber.filter.tags="@UITest" -Dthread.count=$THREAD_COUNT
  artifacts:
    paths:
      - .
    expire_in: 1 week

test_remote_all_UI_Tests:
  image: maven:3.8.4-openjdk-17-slim
  stage: test
  services:
    - docker:dind
  script:
    - apt-get update
    - apt-get install -y curl
    - curl -fsSL https://get.docker.com -o get-docker.sh
    - sh get-docker.sh
    - curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    - chmod +x /usr/local/bin/docker-compose
    - docker-compose up -d
    - >
      attempts=0;
      max_attempts=24;
      until [ "$attempts" -eq "$max_attempts" ]; do
        response=$(curl --silent http://localhost:4444/wd/hub/status);
        if [ "$(echo "$response" | jq -r '.value.ready')" = "true" ]; then
          break;
        fi;
        attempts=$((attempts + 1));
        sleep 5;
      done;
      if [ "$attempts" -eq "$max_attempts" ]; then
        echo "Selenium Grid Hub did not become ready in time.";
        exit 1;
      fi
    - SELENIUM_HOST=http://localhost:4444/wd/hub
    - echo $SELENIUM_HOST
    - mvn clean test -Dspring.profiles.active=remote -Dselenium.grid.url=$SELENIUM_HOST -Dcucumber.filter.tags="@UITest" -Dthread.count=$THREAD_COUNT
  artifacts:
    paths:
      - target/
    expire_in: 1 week

test_UI_Tests_Tagged:
  image: markhobson/maven-chrome
  stage: test
  script:
    - mvn clean test -Dcucumber.filter.tags="@TextBoxTest or @CheckBoxTest" -Dthread.count=$THREAD_COUNT
  artifacts:
    paths:
      - .
    expire_in: 1 week

test_API_Tests:
  image: markhobson/maven-chrome
  stage: test
  script:
    - mvn clean test -Dcucumber.filter.tags="@APITest" -Dthread.count=$THREAD_COUNT
  artifacts:
    paths:
      - .
    expire_in: 1 week

test_API_Tests_Tagged:
  image: markhobson/maven-chrome
  stage: test
  script:
    - mvn clean test -Dcucumber.filter.tags="@APITest and not @DeleteAPITest" -Dthread.count=$THREAD_COUNT
  artifacts:
    paths:
      - .
    expire_in: 1 week

report_all_UI_Tests:
  image: maven:3.8.4-openjdk-17-slim
  stage: report
  script:
    - mvn cluecumber-report:reporting
  artifacts:
    paths:
      - target/full/
    expire_in: 1 week
    when: always
  needs: [ test_all_UI_Tests ]

report_remote_all_UI_Tests:
  image: maven:3.8.4-openjdk-17-slim
  stage: report
  script:
    - mvn cluecumber-report:reporting
  artifacts:
    paths:
      - target/full/
    expire_in: 1 week
    when: always
  needs: [ test_remote_all_UI_Tests ]

report_UI_Tests_Tagged:
  image: maven:3.8.4-openjdk-17-slim
  stage: report
  script:
    - mvn cluecumber-report:reporting
  artifacts:
    paths:
      - target/full/
    expire_in: 1 week
    when: always
  needs: [ test_UI_Tests_Tagged ]

report_API_Tests:
  image: maven:3.8.4-openjdk-17-slim
  stage: report
  script:
    - mvn cluecumber-report:reporting
  artifacts:
    paths:
      - target/full/
    expire_in: 1 week
    when: always
  needs: [ test_API_Tests ]

report_API_Tests_Tagged:
  image: maven:3.8.4-openjdk-17-slim
  stage: report
  script:
    - mvn cluecumber-report:reporting
  artifacts:
    paths:
      - target/full/
    expire_in: 1 week
    when: always
  needs: [ test_API_Tests_Tagged ]
