# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence

stages:
  - test
  - report

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  DOCKER_HOST: tcp://docker:2375
  RUNNER_IP:

before_script:
  - export DOCKER_HOST

test_a:
  image: markhobson/maven-chrome
  stage: test
  script:
    - echo "######### THREAD COUNT IS = $THREAD_COUNT ######## "
    - mvn clean test -Dcucumber.filter.tags="@UITest" -Dthread.count=$THREAD_COUNT
  artifacts:
    paths:
      - .
    expire_in: 1 week

test_b:
  image: maven:3.8.4-openjdk-17-slim
  stage: test
  services:
    - docker:dind
  script:
    - apt-get update
    - apt-get install -y curl
    - curl -fsSL https://get.docker.com -o get-docker.sh
    - sh get-docker.sh
    - curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    - chmod +x /usr/local/bin/docker-compose
    - docker-compose up -d
    - sleep 60 # Wait for the containers to start
    - HUB_HOST=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' selenium-spring-cucumber_hub_1)
    - SELENIUM_HOST=http://$HUBHOST:4444/wd/hub
    - echo SELENIUM_HOST
    - mvn clean test -Dspring.profiles.active=remote -Dcucumber.filter.tags="@UITest" -Dselenium.grid.url=$SELENIUM_HOST -Dthread.count=$THREAD_COUNT
  artifacts:
    paths:
      - target/
    expire_in: 1 week

test_c:
  image: markhobson/maven-chrome
  stage: test
  script:
    - mvn clean test -Dcucumber.filter.tags="@TextBoxTest or @CheckBoxTest" -Dthread.count=$THREAD_COUNT
  artifacts:
    paths:
      - .
    expire_in: 1 week

test_d:
  image: markhobson/maven-chrome
  stage: test
  script:
    - mvn clean test -Dcucumber.filter.tags="@APITest" -Dthread.count=$THREAD_COUNT
  artifacts:
    paths:
      - .
    expire_in: 1 week

test_e:
  image: markhobson/maven-chrome
  stage: test
  script:
    - mvn clean test -Dcucumber.filter.tags="@APITest and not @DeleteAPITest" -Dthread.count=$THREAD_COUNT
  artifacts:
    paths:
      - .
    expire_in: 1 week

report_a:
  image: maven:3.8.4-openjdk-17-slim
  stage: report
  script:
    - mvn cluecumber-report:reporting
  artifacts:
    paths:
      - target/full/
    expire_in: 1 week
    when: always
  needs: [test_a]

report_b:
  image: maven:3.8.4-openjdk-17-slim
  stage: report
  script:
    - mvn cluecumber-report:reporting
  artifacts:
    paths:
      - target/full/
    expire_in: 1 week
    when: always
  needs: [test_b]

report_c:
  image: maven:3.8.4-openjdk-17-slim
  stage: report
  script:
    - mvn cluecumber-report:reporting
  artifacts:
    paths:
      - target/full/
    expire_in: 1 week
    when: always
  needs: [test_c]

report_d:
  image: maven:3.8.4-openjdk-17-slim
  stage: report
  script:
    - mvn cluecumber-report:reporting
  artifacts:
    paths:
      - target/full/
    expire_in: 1 week
    when: always
  needs: [test_d]

report_e:
  image: maven:3.8.4-openjdk-17-slim
  stage: report
  script:
    - mvn cluecumber-report:reporting
  artifacts:
    paths:
      - target/full/
    expire_in: 1 week
    when: always
  needs: [test_e]
